### ISSUE TITLE
stencilmask doesn’t work properly

### ISSUE THREAD

**Issue by hawk86104** [JaimeTorrealba/creative-lab#1]
https://lab.jaimetorrealba.com/stencilmask
The stencil mask in this scene in Three.js encounters issues when it exceeds 0.162.

thx

**Comment by hawk86104** [comment]
I found the solution.
stencil is false
```
<TresCanvas  stencil>
```

**Comment by JaimeTorrealba** [comment]
I upload some changes with the fix, thanks for spot this :)
